language: python
python:
- '2.7'
before_install:
- sudo -H apt-get update -qq
- sudo -H cat requirements.system | sudo xargs apt-get -y install
install:
- pip install -r requirements.txt
- pip install -r requirements.dev
script:
- make build
deploy:
  provider: releases
  api_key:
    secure: JTrhJ59Azk+CpuoF83uIyBBbxdMdtTko+2PctuJT+L5q84KAUb37630pxCm/FyxQ7Z/7SE4xFgsd+svkEWuMj3hj7wVP7bzQGNlRSpiXtFuKTqpdj2P/EFbYHbzJlWv6VP8p0YGkFso+d155v71kzCexuHAev6uOY7OYD+PunaQvetkfOyyXHtm2huxNvxyuZqm7vM2giF9GKoZBCQe0D3Ji2drrRxcWpL9gUYQgLzANdLHzwsTZRf2H2u4FMun97AhyFIV0rfc638ATalfNdf9Qbvxlvexc9zw24BgNYkYkZg35H/J5+AuuNZksZA5Jf7j1rrWdbq8vu1EqbW+AqBsVqtaNe0w5CuBwY45nY9qRqr8fzT66pmoi35LOzVPpZxH7vU8kzyVk/ZWKiLiFwPhTE19sZ1CwwcD4BQM4G5n5XnXR2jwOsW9xq0AhA7XLtyQ9HIF7vzVmfs99qLsJgc45w2YpX1SZinjxTHrM6Qc5+pTSbFHVgdyaM1CZNZLese80oJa9yMT9HZ52QdL4zLtKIGaJxF+bU1O0CCTPJdkQ91eQms1vnIcu/MXgLYCb+AASdj576waiG+4+TOQz0uDSv7i/zfQZ7hdRRg0C62NrvhK9Qe1dT/Wb8TEAvu5YBQqdG/i2FiQ86baRMrve0e423kUnSqHmrSpjmF4YXyo=
  file: dist/*.tar.gz
  on:
    repo: testcraftsman/testpool-client
